service: check for service name validity
The script used not to check for this, causing "service" with no argument
to report ugly errors due to [ -x /sbin/init.d/$svc ] being valid...

diff --git a/sbin/service b/sbin/service
--- a/sbin/service
+++ b/sbin/service
@@ -29,7 +29,12 @@ norm_cfg() {
 }
 
 svc="$1" ; shift
-if [ ! -x "/sbin/init.d/$svc" ]; then
+if [ -z "$svc" ]; then
+  echo "Missing service name"
+  exit 1
+fi
+
+if [ ! -f "/sbin/init.d/$svc" -o ! -x "/sbin/init.d/$svc" ]; then
   echo "Service not found : $svc"
   exit 1
 fi
