* functions: minor code simplification in default_service
we don't check for the functions existence anymore inside the loop.
There was a dirty trick consisting in undeclaring a function to
call it only once. A flag is used now.

diff --git a/sbin/init.d/functions b/sbin/init.d/functions
--- a/sbin/init.d/functions
+++ b/sbin/init.d/functions
@@ -132,7 +132,8 @@ while [ $# -gt 0 ] ; do
     esac
 done
 
-# Assign the requested action to ACTION (first arg). Default : start
+# Assign the requested action to ACTION (first arg), and check for internal
+# ones. Default action : start.
 ACTION=${1:-start}; shift
 
 # Assign the requested instances to SVC_INSTANCE. Default : ""
@@ -753,12 +754,12 @@ default_service() {
 	fi
 
 	# try to insert command-line options
-	while [ "$FORCE_OPTIONS" ]; do  # "opt=val,opt=val..."
+	while [ -n "$FORCE_OPTIONS" ]; do  # "opt=val,opt=val..."
 	    opt=${FORCE_OPTIONS%%,*}
 	    val=${opt#*=}
 	    opt=${opt%%=*}
 	    eval $opt $val
-	    if [ "${FORCE_OPTIONS%%*,*}" ]; then # no more ','
+	    if [ -n "${FORCE_OPTIONS%%*,*}" ]; then # no more ','
 		break;
 	    else
 		FORCE_OPTIONS=${FORCE_OPTIONS#*,}
@@ -779,43 +780,19 @@ default_service() {
 	declare -F fct_end_section > /dev/null && fct_end_section $PNAME ${SVC_ARGS[*]}
 
 	ret=0
-	if [ "$SVC_AUTO_START" = 0 -o "$autostart" = 1 ]; then
-	    if declare -f do_$ACTION >/dev/null; then
-		case $ACTION in
-			getsec|getconf|setsec|setconf|checksec|checkconf|cancelsec|cancelconf|testsec|autostart)
-				if [ "x${SVC_INSTANCE[0]}" = "x" ] ; then
-				# if no instances in args, execute do_$ACTION
-				# only one time for those actions
-					do_$ACTION $PNAME <&3 3>/dev/null
-					ret=$?
-					unset -f do_$ACTION
-				else
-				# else process as std case
-					do_$ACTION $PNAME ${SVC_ARGS[*]} <&3 3>/dev/null
-					ret=$?
-				fi
-				;;
-			*)
-				# std case
-				do_$ACTION $PNAME ${SVC_ARGS[*]} <&3 3>/dev/null
-				ret=$?
-				;;
-		esac
 
-	    else
-		case $ACTION in
-			getsec|getconf|setsec|setconf|checksec|checkconf|cancelsec|cancelconf|testsec|autostart) ;;
-			*)
-				if declare -f do_help >/dev/null; then
-				    	do_help
-				else
-		   			echo "Error: Unknown action : $ACTION"
-				fi
-				((0))  # report an error
-				ret=$?
-				;;
-		esac
-	    fi
+	# Sections marked "no autostart" are skipped on "--auto".
+	# Internal actions are only called once if the instance is not set.
+	if [ "$SVC_AUTO_START" = 0 -o "$autostart" = 1 ]; then
+		if [ -n "$ACT_INTERNAL" -a -z "${SVC_INSTANCE[0]}" ] ; then
+			[ -z "$ACT_DONE" ] && do_$ACTION $PNAME <&3 3>/dev/null
+			ret=$?
+			ACT_DONE=set
+		else
+			# std case
+			do_$ACTION $PNAME ${SVC_ARGS[*]} <&3 3>/dev/null
+			ret=$?
+		fi
 	fi
 
 	if [ $ret -gt 0 ]; then
@@ -1234,13 +1211,7 @@ default_no() {
     local req=$1
     shift
     case "$req" in
-	"service")
-	    default_service
-	    ;;
-	"section")
-	    default_service
-	    ;;
-        "interface")
+	service|section|interface)
 	    default_service
 	    ;;
 	*)
@@ -1325,6 +1296,24 @@ load_config() {
 ###################################################################
 # Second half of main entry point. Declaration of default options #
 ###################################################################
+
+# We already know if the action is known or not, it's not necessary
+# to parse all the config to find that.
+if ! declare -f do_$ACTION >/dev/null; then
+    if declare -f do_help >/dev/null; then
+    	do_help
+    else
+	echo "Error: Unknown action : $ACTION"
+    fi
+fi
+
+# ACT_INTERNAL is set for internal actions.
+unset ACT_INTERNAL ACT_DONE
+case $ACTION in
+    getsec|getconf|setsec|setconf|checksec|checkconf|cancelsec|cancelconf|testsec|autostart)
+	ACT_INTERNAL=set
+	;;
+esac
 
 # most services don't need to redefine the keywords "bin", "cmdline",
 # "pidfile", "procname" and "check_interval", so let's initialize them now.
