network: show errors when trying to enslave an incompatible interface
Trying to attach certain devices to a bridge fails. Unfortunately the
errors are silently hidden for now. This patch makes them visible and
prints an error when this happens.

diff --git a/sbin/init.d/network b/sbin/init.d/network
--- a/sbin/init.d/network
+++ b/sbin/init.d/network
@@ -481,7 +481,9 @@ function do_start {
                            $0 start $arg ) >/dev/null 2>&1; then
                         echo "  ==> FAILED! need to start iface $arg before $instname"
                     else
-                        ip link set dev $arg master $instname >/dev/null 2>&1
+                        if ! ip link set dev $arg master $instname; then
+                            echo "  ==> Failed to add slave $arg to bridge $instname"
+                        fi
                         ip addr flush dev $arg >/dev/null 2>&1
                     fi
             done
